2023-03-15 18:59:45,090 INFO    MainThread:7852 [wandb_setup.py:_flush():76] Configure stats pid to 7852
2023-03-15 18:59:45,090 INFO    MainThread:7852 [wandb_setup.py:_flush():76] Loading settings from /Users/aneeshaparajit/.config/wandb/settings
2023-03-15 18:59:45,090 INFO    MainThread:7852 [wandb_setup.py:_flush():76] Loading settings from /Users/aneeshaparajit/Desktop/NASSCOM-TAIM/pix2pix_rnn/src/aqiai/notebooks/wandb/settings
2023-03-15 18:59:45,090 INFO    MainThread:7852 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-03-15 18:59:45,090 INFO    MainThread:7852 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-03-15 18:59:45,090 WARNING MainThread:7852 [wandb_setup.py:_flush():76] Could not find program at NASSCOM-TAIM/pix2pix_rnn/src/aqiai/notebooks/3f60be95-c887-451f-a2c2-0cc41c1d76a7
2023-03-15 18:59:45,090 INFO    MainThread:7852 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': None, 'program': 'NASSCOM-TAIM/pix2pix_rnn/src/aqiai/notebooks/3f60be95-c887-451f-a2c2-0cc41c1d76a7'}
2023-03-15 18:59:45,090 INFO    MainThread:7852 [wandb_init.py:_log_setup():506] Logging user logs to /Users/aneeshaparajit/Desktop/NASSCOM-TAIM/pix2pix_rnn/src/aqiai/notebooks/wandb/run-20230315_185945-v8truopl/logs/debug.log
2023-03-15 18:59:45,090 INFO    MainThread:7852 [wandb_init.py:_log_setup():507] Logging internal logs to /Users/aneeshaparajit/Desktop/NASSCOM-TAIM/pix2pix_rnn/src/aqiai/notebooks/wandb/run-20230315_185945-v8truopl/logs/debug-internal.log
2023-03-15 18:59:45,090 INFO    MainThread:7852 [wandb_init.py:init():546] calling init triggers
2023-03-15 18:59:45,090 INFO    MainThread:7852 [wandb_init.py:init():552] wandb.init called with sweep_config: {}
config: {'seed': 42, 'exp_name': 'nasscom-taim', 'model_name': 'pix2pix-rnn-aqi', 'base_model': 'None', 'train_bs': 1, 'valid_bs': 1, 'image_size': [224, 224], 'in_channels': 1, 'latent_size': 128, 'hidden_size': 512, 'num_layers': 2, 'bidirectional': 0, 'comment': 'model-pix2pix-rnn-aqi|latent_size-128|info_channels-1|hidden_dim-512|num_layers-2|bidirectional-0|dim-224x224', 'epochs': 100, 'learning_rate': 0.0003, 'scheduler': 'CosineAnnealingLR', 'min_lr': 1e-06, 'T_max': 3000050, 'T_0': 25, 'warmup_epochs': 0, 'wd': 1e-06, 'n_accumulate': 32, 'n_fold': 5, 'num_classes': 3, 'device': device(type='cpu'), 'trial_num': 1}
2023-03-15 18:59:45,090 INFO    MainThread:7852 [wandb_init.py:init():568] re-initializing run, found existing run on stack: 0h15v6xc
2023-03-15 18:59:45,093 INFO    MainThread:7852 [wandb_run.py:_finish():1852] finishing run aaparajit02/nasscom-taim/0h15v6xc
2023-03-15 18:59:45,093 INFO    MainThread:7852 [jupyter.py:save_history():445] not saving jupyter history
2023-03-15 18:59:45,094 INFO    MainThread:7852 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-03-15 18:59:45,094 INFO    MainThread:7852 [wandb_init.py:_jupyter_teardown():434] cleaning up jupyter logic
2023-03-15 18:59:45,094 INFO    MainThread:7852 [wandb_run.py:_atexit_cleanup():2081] got exitcode: 0
2023-03-15 18:59:45,095 INFO    MainThread:7852 [wandb_run.py:_restore():2064] restore
2023-03-15 18:59:45,095 INFO    MainThread:7852 [wandb_run.py:_restore():2070] restore done
2023-03-15 19:03:10,323 INFO    MainThread:7852 [wandb_init.py:init():602] starting backend
2023-03-15 19:03:10,324 INFO    MainThread:7852 [wandb_init.py:init():606] setting up manager
2023-03-15 19:03:10,331 INFO    MainThread:7852 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2023-03-15 19:03:10,332 INFO    MainThread:7852 [wandb_init.py:init():613] backend started and connected
2023-03-15 19:03:10,346 INFO    MainThread:7852 [wandb_run.py:_label_probe_notebook():1202] probe notebook
2023-03-15 19:03:10,347 INFO    MainThread:7852 [wandb_run.py:_label_probe_notebook():1212] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-03-15 19:03:10,347 INFO    MainThread:7852 [wandb_init.py:init():701] updated telemetry
2023-03-15 19:03:10,367 INFO    MainThread:7852 [wandb_init.py:init():741] communicating run to backend with 60.0 second timeout
